area:
  regionCode: '5E61480'
  radius: 0.0
parameters:
  minPrice: 50000
  maxPrice: 260000
  minBedrooms: 1
  maxBedrooms:
  maxDaysSinceAdded:
  onlyAuction: false
  includeSSTC: false
  dontShow:
    - newHome
    - retirement
    - sharedOwnership
  mustHave:
