area:
  regionCode: '5E61480'
  radius: 0.0
parameters:
  minPrice:
  maxPrice: 260000
  minBedrooms: 1
  maxBedrooms:
  maxDaysSinceAdded:
  onlyAuction:
  includeSSTC:
  dontShow:
    retirement
  mustHave:
